### ISSUE TITLE
Exception: Unknown type mdb

### ISSUE THREAD

**Issue by drprajapati** [kayoyin/FakeCelebs#4]
[ Torchvision_sunner ] Applied <<          Resize >>
[ Torchvision_sunner ] * Notice: the rank format of input tensor should be 'BHWC'
[ Torchvision_sunner ] Applied <<        ToTensor >>
[ Torchvision_sunner ] Applied <<         ToFloat >>
[ Torchvision_sunner ] Applied <<       Transpose >>, The rank format is BCHW
[ Torchvision_sunner ] Applied <<       Normalize >>
[ Torchvision_sunner ] * Notice: the rank format of input tensor should be 'BCHW'
[ Torchvision_sunner ] *****************************************************************
[ Torchvision_sunner ] * Notice: You should must call 'ToFloat' before normalization
[ Torchvision_sunner ] *****************************************************************
[ Torchvision_sunner ] * Notice: The result will locate in [-1, 1]
[ Torchvision_sunner ] ==================================================
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    [sunnertransforms.Resize((128, 128)), sunnertransforms.ToTensor(), sunnertransforms.ToFloat(), sunnertransforms.Transpose(sunnertransforms.BHWC2BCHW), sunnertransforms.Normalize()]
  File "/home/robotics/TeamMercury/FakeCelebs-master/torchvision_sunner/data/image_dataset.py", line 67, in __init__
    self.getFiles()
  File "/home/robotics/TeamMercury/FakeCelebs-master/torchvision_sunner/data/image_dataset.py", line 126, in getFiles
    images += readContain(img)
  File "/home/robotics/TeamMercury/FakeCelebs-master/torchvision_sunner/read.py", line 39, in readContain
    raise Exception("Unknown type {}, You should customize in read.py".format(common_type))
Exception: Unknown type mdb, You should customize in read.py

**Comment by guanguanboy** [comment]
me too

**Comment by FrazierLei** [comment]
Have you solved this problem?
